

server:
  port: 8080
spring:
  data:
    cassandra:
      contact-points:
      - 127.0.0.1
      port: 9042
      keyspace-name: demo
      schema-action: CREATE_IF_NOT_EXISTS
logging:
    level:
      com.datastax.driver.core.QueryLogger.NORMAL: DEBUG
      com.datastax.driver.core.QueryLogger.SLOW: TRACE